language: python
python:
  - '3.7.3'
install: 
  - pip install -r requirements.txt
  - pip install coveralls
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test_nbox;" -U postgres
  - psql -c "CREATE USER antoo WITH PASSWORD 'antoo123';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE test_nbox to antoo;" -U postgres
  
script: 
  - pytest --cov-report term-missing --cov=db_config
  
after_success:
  - coveralls
  
cache: pip